import { PrinciplePage } from "../PrinciplePage";

export default function StrategicIntelligencePage() {
  return <PrinciplePage
    zh={{
      back: "← 返回研究主页", toggle: "EN", eyebrow: "公理原理 · 03 / 谋算智能（MSI）",
      title: "谋算智能\n从计算走向谋与算。",
      lead: "谋算智能（MouSuan Intelligence, MSI）由两种互补策略生成：层谱抽象的全局认知（编码），以及面向推理与行动的演算（计算）。",
      sections: [["谋算智能的定义", "谋算智能是由“谋”与“算”共同生成的智能：以层谱抽象建立全局认知，以演算和推理跨越抽象层谱，再以计算形成可执行的决策与行动。"], ["谋（Mou）· 层谱抽象的全局认知", "“谋”是信息科学概念：通过层谱抽象、编码与全局识别，把复杂世界组织成可观察、可解码、可推演的结构。它回答“世界是什么、关系如何组织”。"], ["谋（Mou）· 跨层谱演算与推理", "谋不仅是抽象，还要在不同抽象层之间演算与推理，使局部事实能够回到整体、整体目标能够落到局部行动。"], ["算（Suan）· 分而治之的计算", "“算”是经典数学与物理中的计算概念：通过分而治之（divide-and-conquer）拆解问题、计算关系、聚合结果，把认知转化为可验证的策略。"], ["谋算双脑体系结构", "谋脑负责层谱抽象与全局认知，算脑负责分而治之与演算推理；二者组成谋算双脑体系结构智能机器，形成观察、解码、计算、决策、行动与验证的闭环。"]],
      sourcesLabel: "原始论文与阅读入口",
      sources: [["Hierarchical Decision Making Based on Structural Information Principles · JMLR", "https://jmlr.org/papers/volume26/24-1184/24-1184.pdf"], ["关于我们 · 李昂生教授团队", "/#about"]],
      closing: "这是一页面向公众的概念说明；论文与团队主页提供正式研究细节。",
    }}
    en={{
      back: "← Back to research hub", toggle: "中", eyebrow: "PRINCIPLES · 03 / MOUSUAN INTELLIGENCE (MSI)",
      title: "MouSuan Intelligence\nfrom recognition to calculation.",
      lead: "MouSuan Intelligence (MSI) is generated by two complementary strategies: hierarchical abstraction for global recognition (encoding), and calculating for reasoning and action (computing).",
      sections: [["The definition", "MouSuan Intelligence is generated by Mou and Suan together: hierarchical abstraction creates global recognition; calculus and reasoning cross abstraction levels; calculation turns that recognition into executable decisions and actions."], ["Mou · hierarchical abstraction and global cognition", "Mou is an information-science concept. Through hierarchical abstraction, encoding, and global recognition, it organises a complex world into structures that can be observed, decoded, and inferred. It asks: what is the world, and how are its relations organised?"], ["Mou · cross-level reasoning", "Mou is not abstraction alone. It calculates and reasons across levels of abstraction, returning local facts to the whole and bringing global objectives down to local action."], ["Suan · divide-and-conquer calculation", "Suan is the classical mathematical and physical idea of calculation. Through divide-and-conquer, it decomposes problems, computes relations, and aggregates results into a verifiable strategy."], ["The MouSuan dual-brain architecture", "The Mou brain performs hierarchical abstraction and global recognition; the Suan brain performs divide-and-conquer calculation and reasoning. Together they form MouSuan dual-brain architecture intelligent machines: observe, decode, calculate, decide, act, and verify."]],
      sourcesLabel: "ORIGINAL SOURCES",
      sources: [["Hierarchical Decision Making Based on Structural Information Principles · JMLR", "https://jmlr.org/papers/volume26/24-1184/24-1184.pdf"], ["About us · Angsheng Li’s research team", "/#about"]],
      closing: "This is a public-facing concept page; the paper and team homepage provide the formal research details.",
    }}
  />;
}
