import { PrinciplePage } from "../PrinciplePage";

export default function StrategicIntelligencePage() {
  return <PrinciplePage
    zh={{
      back: "← 返回研究主页", toggle: "EN", eyebrow: "公理原理 · 03 / 谋算智能（MSI）",
      title: "谋算智能\n从计算走向谋与算",
      lead: "谋算智能（MouSuan Strategy, MSI）由两种互补策略生成：层谱抽象的全局认知（编码），以及面向推理与行动的演算（计算）。",
      sections: [["谋算智能的定义", "谋算智能是由“谋”与“算”共同生成的智能：以层谱抽象建立全局认知，以演算和推理跨越抽象层谱，再以计算形成可执行的决策与行动。"], ["谋（Mou）· 层谱抽象的全局认知", "“谋”是信息科学概念：通过层谱抽象、编码与全局认知，把复杂世界组织成可观察、可解码、可推演的结构。它回答“世界是什么、关系如何组织”。"], ["谋（Mou）· 跨层谱演算与推理", "谋不仅是抽象，还要在不同抽象层之间演算与推理，使局部事实能够回到整体、整体目标能够落到局部行动。"], ["算（Suan）· 分而治之的计算", "“算”是经典数学与物理中的计算概念：通过分而治之（divide-and-conquer）拆解问题、计算关系、聚合结果，把认知转化为可验证的策略。"], ["谋算双脑体系结构", "谋脑负责层谱抽象与全局认知，算脑负责分而治之与演算推理；二者组成谋算双脑体系结构智能机，形成观察、解码、计算、决策、行动与验证的闭环。"]],
      sourcesLabel: "原始论文与阅读入口",
      sources: [["Hierarchical Decision Making Based on Structural Information Principles · JMLR", "https://jmlr.org/papers/volume26/24-1184/24-1184.pdf"], ["书籍与购买链接", "/books/"], ["关于我们 · 李昂生教授团队", "/#about"]],
      closing: "这是一页面向公众的概念说明；论文与团队主页提供正式研究细节。",
    }}
    en={{
      back: "← Back to research hub", toggle: "中", eyebrow: "PRINCIPLES · 03 / MOUSUAN STRATEGY (MSI)",
      title: "MouSuan Strategy\nfrom abstraction to calculation.",
      lead: "MouSuan Strategy (MSI) is generated by two complementary strategies: Mou—hierarchical abstracting recognition, calculating that crosses the hierarchies of abstracting, and updating the encoding tree—and Suan—computing and calculating, which is a strategy of logical reasoning.",
      sections: [["The definition", "MouSuan Strategy is generated by Mou and Suan together: Mou performs hierarchical abstracting global recognition, crosses the hierarchies of abstracting through calculation, and updates the encoding tree; Suan performs computing and calculating as a strategy of logical reasoning."], ["Mou · hierarchical abstracting recognition", "Mou is an information-science concept: hierarchical abstracting recognition whose mathematical model is the encoding tree. Mou organises the information world globally, crosses the hierarchies of abstracting, and updates the encoding tree."], ["Mou · cross-hierarchy calculating", "Mou calculates across the hierarchies of abstracting, returning local facts to the whole and bringing global objectives down to local action while updating the encoding tree."], ["Suan · computing and calculating", "Suan means computing and calculating, which is a strategy of logical reasoning. It decomposes relations and problems, computes their consequences, and aggregates results into verifiable strategy."], ["The MouSuan dual-brain architecture", "The Mou brain performs hierarchical abstracting global recognition, cross-hierarchy calculating, and encoding-tree updating; the Suan brain performs computing and calculating as a strategy of logical reasoning. Together they form MouSuan dual-brain architecture intelligent machines: observe, decode, calculate, decide, act, and verify."]],
      sourcesLabel: "ORIGINAL SOURCES",
      sources: [["Hierarchical Decision Making Based on Structural Information Principles · JMLR", "https://jmlr.org/papers/volume26/24-1184/24-1184.pdf"], ["Books & purchase links", "/books/"], ["About us · Angsheng Li’s research team", "/#about"]],
      closing: "This is a public-facing concept page; the paper and team homepage provide the formal research details.",
    }}
  />;
}
