from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import LongTable, PageBreak, Paragraph, SimpleDocTemplate, Spacer, TableStyle


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "output" / "pdf" / "mousuan-terminology-review.pdf"
OUTPUT.parent.mkdir(parents=True, exist_ok=True)


def register_cjk_font() -> str:
    candidates = [
        ("/System/Library/Fonts/STHeiti Medium.ttc", 0),
        ("/System/Library/Fonts/Hiragino Sans GB.ttc", 0),
        ("/Library/Fonts/Arial Unicode.ttf", None),
    ]
    for path, subfont_index in candidates:
        if not Path(path).exists():
            continue
        try:
            if subfont_index is None:
                pdfmetrics.registerFont(TTFont("ReviewCJK", path))
            else:
                pdfmetrics.registerFont(TTFont("ReviewCJK", path, subfontIndex=subfont_index))
            return "ReviewCJK"
        except Exception:
            continue
    raise RuntimeError("No usable Chinese-capable font was found")


FONT = register_cjk_font()
PAGE_W, PAGE_H = landscape(A4)

styles = getSampleStyleSheet()
title_style = ParagraphStyle(
    "TitleReview",
    parent=styles["Title"],
    fontName=FONT,
    fontSize=20,
    leading=25,
    alignment=TA_CENTER,
    textColor=colors.HexColor("#0b1230"),
    spaceAfter=4 * mm,
)
subtitle_style = ParagraphStyle(
    "SubtitleReview",
    parent=styles["Normal"],
    fontName=FONT,
    fontSize=9,
    leading=12,
    alignment=TA_CENTER,
    textColor=colors.HexColor("#5d6782"),
    spaceAfter=6 * mm,
)
header_style = ParagraphStyle(
    "HeaderReview",
    parent=styles["Normal"],
    fontName=FONT,
    fontSize=9,
    leading=11,
    alignment=TA_CENTER,
    textColor=colors.white,
)
cell_style = ParagraphStyle(
    "CellReview",
    parent=styles["Normal"],
    fontName=FONT,
    fontSize=8.2,
    leading=11,
    alignment=TA_LEFT,
    textColor=colors.HexColor("#17203b"),
)
term_style = ParagraphStyle(
    "TermReview",
    parent=cell_style,
    fontSize=8.6,
    leading=11.5,
    textColor=colors.HexColor("#111b42"),
)
english_style = ParagraphStyle(
    "EnglishReview",
    parent=cell_style,
    fontName="Helvetica",
    fontSize=8.1,
    leading=10.8,
    textColor=colors.HexColor("#263154"),
)


def p(text: str, style=cell_style) -> Paragraph:
    return Paragraph(text.replace("&", "&amp;"), style)


rows = [
    ("谋算智能", "MouSuan Strategy (MSI)", "由“谋”与“算”两种互补策略结合生成的智能：谋进行层谱抽象的全局认知与推理、跨越抽象层谱的演算与推理并更新编码树；算进行计算与逻辑推理。", "The intelligence that is generated by combining Mou and Suan: Mou performs hierarchically abstracting global recognition and reasoning, calculating and reasoning that cross the hierarchies of abstracting, and encoding-tree updating; Suan performs computing and calculating as a strategy of logical reasoning."),
    ("智", "Strategically designing", "智能中的“智”：认知与策略设计的科学原理，负责从信息中形成可解释的策略设计。", "“Zhi” refers to the scientific principles of cognition and strategic design."),
    ("能", "Efficiently acting", "智能中的“能”：有效行动的工程原理与执行能力，把策略落实为可验证的行动。", "“Neng” refers to the engineering principles and capability for effective action."),
    ("智能", "Intelligence", "“智”与“能”的统一：既能进行策略设计，又能有效行动。智能需要行动。", "Intelligence, in the Chinese sense, is the unity of the two: strategically designing and efficiently acting. Intelligence requires action."),
    ("谋", "Mou", "层谱抽象的全局认知与推理；数学模型是编码树，属于信息科学概念。", "- Hierarchically abstracting recognition<br/>- Calculating and reasoning that cross the hierarchies of abstracting<br/>- Updating the encoding tree<br/>- Mou is a strategy of hierarchically abstracting global recognition and reasoning"),
    ("算", "Suan", "计算与分而治之；属于经典数学、物理概念，把问题拆解并聚合结果。", "- Computing<br/>- Calculating<br/>- Computing and calculating, which is a strategy of logical reasoning"),
    ("层谱抽象", "hierarchically abstracting", "跨越层级组织复杂世界，形成能够被观察、编码并表示为数据结构的组织。", "Organising a complex world across a spectrum of hierarchies so that it can be observed, encoded, and represented as a data structure."),
    ("编码树", "encoding tree", "层谱抽象的数学模型，用树结构表示从局部到整体的层级组织。", "The mathematical model of hierarchically abstracting, representing an organisation from local parts to the whole as a tree."),
    ("全局认知", "global recognition and reasoning", "从整体结构与关系出发认知并推理信息世界，而不只拟合局部相关性。", "Understanding and reasoning about the information world from the whole-system structure and relations, rather than from local correlations alone."),
    ("跨越抽象层谱的演算与推理", "calculating and reasoning that cross the hierarchies of abstracting", "在不同抽象层之间传递信息、进行演算与推理，使整体目标能够落到局部行动。", "Calculating and reasoning that cross the hierarchies of abstracting so that information and global objectives can reach local action."),
    ("更新编码树", "updating the encoding tree", "依据新的观察、结构和策略结果更新编码树。", "Updating the encoding tree from new observations, structures, and strategy results."),
    ("计算", "Computing / Calculating", "对关系、状态与策略进行可执行、可验证的运算。", "Computing and calculating, which is a strategy of logical reasoning over relations, states, and strategies."),
    ("分而治之", "divide-and-conquer", "把复杂问题拆成子问题，分别计算，再组合为整体结果。", "Decomposing a complex problem into subproblems, solving them, and combining the results."),
    ("策略", "Strategy", "一种行动、操作或者算子。", "An action, an operation, or an operator."),
    ("生成策略", "Generating strategy", "生成信息的策略。", "A strategy that generates information."),
    ("解码策略", "Decoding strategy", "解码信息或消除不确定性的策略。", "A strategy to decode information or eliminate uncertainty."),
    ("公理化科学原理", "Axiomatized Science Principles", "以公理或定律、定义和可验证推论组织科学知识体系。", "A scientific knowledge system organised by axioms or law, definitions, and verifiable deductions."),
    ("信息科学", "information science", "研究信息的表示、演算、解码、生成及其在系统中的组织规律。", "The study of how information is represented, calculated, decoded, generated, and organised in systems."),
    ("谋算双脑体系结构", "MouSuan dual-brain architecture", "谋脑负责层谱抽象的全局认知与推理、跨越抽象层谱的演算与推理和编码树更新；算脑负责计算与逻辑推理，二者形成闭环。", "An architecture in which the Mou brain performs hierarchically abstracting global recognition and reasoning, calculating and reasoning that cross the hierarchies of abstracting, and encoding-tree updating, while the Suan brain performs computing and calculating as a strategy of logical reasoning."),
    ("谋算智能机", "MouSuan intelligent machine", "以谋算智能原理实现观察、解码、生成、计算、决策、行动与验证的智能机。", "An intelligent machine based on MouSuan Strategy that observes, decodes, generates, calculates, decides, acts, and verifies."),
    ("谋算双脑体系结构智能机", "MouSuan dual-brain architecture intelligent machine", "以谋算双脑体系结构实现观察、解码、生成、计算、决策、行动与验证的智能机。", "An intelligent machine that uses the MouSuan dual-brain architecture to observe, decode, generate, calculate, decide, act, and verify."),
    ("孙子模型（谋算系统）", "Sun Tzu Model (MouSuan system)", "基于信息世界科学原理的谋算智能系统；是面向策略设计和有效行动的有原理、可解释世界模型，形成民用版与军用版。", "The Sun Tzu Model is a model of MouSuan Strategy—a principled, explainable model for strategic design and effective action, with civilian and military versions."),
    ("孙子机（谋算机）", "Sun Tzu Machine (MouSuan machine)", "基于信息世界科学原理的谋算双脑体系结构智能机；有原理、可解释的智能机。", "A MouSuan dual-brain architecture intelligent machine based on the scientific principles of the information world; a principled, explainable intelligent machine."),
    ("信息原理的具身智能", "Information-principled embodied intelligence", "以自我意识的信息模型为核心，在真实身体、传感器和环境中观察、学习、行动并验证。", "Embodied intelligence grounded in information principles and an information model of awareness, supporting observation, learning, action, and verification in a body and environment."),
    ("智能机", "intelligent machine", "中文网站统一使用的正式简称；指具备原理、解释与验证能力的智能机。", "The standard Chinese short form for an intelligent machine with principles, explanations, and verification."),
    ("智能机器人", "intelligent robot", "具备身体、传感器和行动能力的智能机；保留“机器人”这一完整术语。", "An intelligent machine with a body, sensors, and physical action; the complete robot term is retained."),
]


def footer(canvas, doc):
    canvas.saveState()
    canvas.setStrokeColor(colors.HexColor("#d8dced"))
    canvas.line(16 * mm, 13 * mm, PAGE_W - 16 * mm, 13 * mm)
    canvas.setFont("Helvetica", 7.5)
    canvas.setFillColor(colors.HexColor("#69738c"))
    canvas.drawString(16 * mm, 8 * mm, "MouSuan Strategy terminology review sheet")
    canvas.drawRightString(PAGE_W - 16 * mm, 8 * mm, f"Page {doc.page}")
    canvas.restoreState()


doc = SimpleDocTemplate(
    str(OUTPUT),
    pagesize=landscape(A4),
    rightMargin=16 * mm,
    leftMargin=16 * mm,
    topMargin=14 * mm,
    bottomMargin=18 * mm,
    title="MouSuan Strategy Terminology Review Sheet",
    author="Structural Information & Artificial Intelligence research team",
)

data = [[p("中文术语", header_style), p("统一英文", header_style), p("中文含义", header_style), p("English meaning", header_style)]]
for zh, en, meaning_zh, meaning_en in rows:
    data.append([p(zh, term_style), p(en, english_style), p(meaning_zh), p(meaning_en, english_style)])

table = LongTable(data, colWidths=[39 * mm, 62 * mm, 78 * mm, 94 * mm], repeatRows=1, splitByRow=1)
table.setStyle(TableStyle([
    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#11152e")),
    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
    ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ("GRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#d8dced")),
    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f7f8fd")]),
    ("LEFTPADDING", (0, 0), (-1, -1), 6),
    ("RIGHTPADDING", (0, 0), (-1, -1), 6),
    ("TOPPADDING", (0, 0), (-1, -1), 6),
    ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
]))

story = [
    Paragraph("谋算智能术语表", title_style),
    Paragraph("MouSuan Strategy Terminology Review Sheet · Chinese–English canonical terms", subtitle_style),
    table,
]
doc.build(story, onFirstPage=footer, onLaterPages=footer)
print(OUTPUT)
