#!/usr/bin/env python3
"""Patch a previously verified static release with terminology-only changes.

This is intentionally limited to exact string substitutions so a known-good
vinext export can be reused when the local legacy build toolchain is unavailable.
"""

from __future__ import annotations

import sys
from pathlib import Path


REPLACEMENTS = [
    (
        "智能不是一个黑箱。它可以被观察、解码、生成、组织、编码，并被赋予可检验的原理。一个自我意识体的智能就是它的信息：智能 = 信息。信息是解码信息世界的钥匙。信息是创建智能科学原理的数学基础。",
        "智能不是一个黑箱。它可以被观察、解码、生成、组织、编码，并被赋予可检验的原理。一个自我意识体的智能就是它的信息：智能 = 信息。信息是解码信息世界的钥匙。信息是创建智能科学原理的数学基础。“智”是策略性设计，“能”是高效行动；智能是二者的统一，智能需要行动。",
    ),
    (
        "Intelligence need not remain a black box. It can be observed, decoded, generated, organised, encoded, and grounded in testable principles. The intelligence of a self-aware subject is its information: intelligence = information. Information is the key to decoding the information world. Information is the mathematical foundation for establishing the principles of intelligent science.",
        "Intelligence need not remain a black box. It can be observed, decoded, generated, organised, encoded, and grounded in testable principles. The intelligence of a self-aware subject is its information: intelligence = information. Information is the key to decoding the information world. Information is the mathematical foundation for establishing the principles of intelligent science. “Zhi” is strategically designing; “Neng” is efficiently acting. Intelligence, in the Chinese sense, is the unity of the two and requires action.",
    ),
    (
        "《孙子兵法》以战争现象为对象，把物质与信息结合为动态演化的体系对抗博弈；孙子模型把它转化为可研究、可设计、可验证的人工智能框架。",
        "《孙子兵法》以战争现象为对象，把物质与信息结合为动态演化的体系对抗博弈；孙子模型把它转化为可研究、可设计、可验证的人工智能框架。孙子模型是谋算智能的模型——一个面向策略设计和有效行动的有原理模型。",
    ),
    (
        "Treating warfare as a system-level, dynamically evolving contest of matter and information, the Sun Tzu model turns the Art of War into a researchable, designable, and verifiable AI framework.",
        "Treating warfare as a system-level, dynamically evolving contest of matter and information, the Sun Tzu model turns the Art of War into a researchable, designable, and verifiable AI framework. The Sun Tzu Model is a model of MouSuan Intelligence—a principled model for strategic design and effective action.",
    ),
    (
        "有原理、可解释的世界模型；形成民用版与军用版。",
        "孙子模型是谋算智能的模型——一个面向策略设计和有效行动的有原理、可解释世界模型；形成民用版与军用版。",
    ),
    (
        "A principled, explainable world model with civilian and military versions.",
        "The Sun Tzu Model is a model of MouSuan Intelligence—a principled, explainable model for strategic design and effective action, with civilian and military versions.",
    ),
    ("基于信息世界科学原理的谋算双脑智能机器", "基于信息世界科学原理的谋算双脑智能机"),
    ("有原理、可解释的智能机器。", "有原理、可解释的智能机。"),
    (
        "Using hierarchical abstraction as the general method,",
        "Using hierarchically abstracting as the general method,",
    ),
    (
        "MouSuan dual-brain architecture intelligent machines combine global cognition, cross-level reasoning, calculation, and autonomous decisions.",
        "MouSuan dual-brain architecture intelligent machines combine global recognition and reasoning, calculating and reasoning that cross the hierarchies of abstracting, computation, and autonomous decisions.",
    ),
    (
        "以战争现象为对象，提出物质与信息结合的公理化科学原理、孙子五大定律、信息军事科学与孙子模型。",
        "以战争现象为对象，提出物质与信息结合的公理化科学原理、孙子五大定律、信息军事科学与孙子模型。孙子模型是谋算智能的模型——一个面向策略设计和有效行动的有原理模型。",
    ),
    (
        "A system of Axiomatized Science Principles combining matter and information, including the five Sun Tzu laws, information military science, and the Sun Tzu model.",
        "A system of Axiomatized Science Principles combining matter and information, including the five Sun Tzu laws and information military science. The Sun Tzu Model is a model of MouSuan Intelligence—a principled model for strategic design and effective action.",
    ),
    (
        "谋算智能（MouSuan Strategy, MSI）由两种互补策略生成：层谱抽象的全局认知（编码），以及面向推理与行动的演算（计算）。",
        "谋算智能由“谋”与“算”两种互补策略结合生成：谋进行层谱抽象的全局认知与推理、跨越抽象层谱的演算与推理并更新编码树；算进行计算与逻辑推理。",
    ),
    (
        "谋算智能是由“谋”与“算”共同生成的智能：以层谱抽象建立全局认知，以演算和推理跨越抽象层谱，再以计算形成可执行的决策与行动。",
        "谋算智能由“谋”与“算”结合生成。“智”是认知与策略设计的科学原理，即策略性设计；“能”是有效行动的工程原理与执行能力，即高效行动。智能是二者的统一，智能需要行动。",
    ),
    (
        "“谋”是信息科学概念：通过层谱抽象、编码与全局识别，把复杂世界组织成可观察、可解码、可推演的结构。它回答“世界是什么、关系如何组织”。",
        "“谋”是信息科学概念：通过层谱抽象、编码、全局认知与推理，把复杂世界组织成能够被观察、编码并表示为数据结构的组织。它回答“世界是什么、关系如何组织”。",
    ),
    (
        "谋脑负责层谱抽象与全局认知，算脑负责分而治之与演算推理；二者组成谋算双脑体系结构智能机，形成观察、解码、计算、决策、行动与验证的闭环。",
        "谋脑负责层谱抽象、全局认知与推理，算脑负责分而治之与演算推理；二者组成谋算双脑体系结构智能机，形成观察、解码、生成、计算、决策、行动与验证的闭环。",
    ),
    (
        "MouSuan Strategy (MSI) is generated by two complementary strategies: Mou—hierarchical abstracting recognition, calculating that crosses the hierarchies of abstracting, and updating the encoding tree—and Suan—computing and calculating, which is a strategy of logical reasoning.",
        "MouSuan Strategy (MSI) is generated by combining two complementary strategies: Mou—hierarchically abstracting global recognition and reasoning, calculating and reasoning that cross the hierarchies of abstracting, and updating the encoding tree—and Suan—computing and calculating as a strategy of logical reasoning.",
    ),
    (
        "MouSuan Strategy is generated by Mou and Suan together: hierarchical abstraction creates global cognition; calculus and reasoning cross abstraction levels; calculation turns that recognition into executable decisions and actions.",
        "The intelligence that is generated by combining Mou and Suan. “Zhi” refers to the scientific principles of cognition and strategic design; “Neng” refers to the engineering principles and capability for effective action. Intelligence, in the Chinese sense, is the unity of the two. Intelligence requires action.",
    ),
    (
        "Mou is an information-science concept: hierarchical abstracting recognition whose mathematical model is the encoding tree. Mou organises the information world globally, crosses the hierarchies of abstracting, and updates the encoding tree.",
        "Mou is an information-science concept. It organises a complex world across a spectrum of hierarchies so that it can be observed, encoded, and represented as a data structure; its mathematical model is the encoding tree.",
    ),
    (
        "Mou calculates across the hierarchies of abstracting, returning local facts to the whole and bringing global objectives down to local action while updating the encoding tree.",
        "Mou calculates and reasons across the hierarchies of abstracting, returning local facts to the whole and bringing global objectives down to local action while updating the encoding tree.",
    ),
    (
        "The Mou brain performs hierarchical abstracting global recognition, cross-hierarchy calculating, and encoding-tree updating; the Suan brain performs computing and calculating as a strategy of logical reasoning. Together they form MouSuan dual-brain architecture intelligent machines: observe, decode, calculate, decide, act, and verify.",
        "The Mou brain performs hierarchically abstracting global recognition and reasoning, calculating and reasoning across the hierarchies of abstracting, and encoding-tree updating; the Suan brain performs computing and calculating as a strategy of logical reasoning. Together they form MouSuan dual-brain architecture intelligent machines that observe, decode, generate, calculate, decide, act, and verify.",
    ),
    (
        "谋脑负责层谱抽象的全局认知，算脑负责分而治之的演算与推理；两脑协同，让机器同时具备理解整体与计算局部的能力。",
        "“智”是认知与策略设计的科学原理，“能”是有效行动的工程原理与执行能力；智能是二者的统一并且需要行动。谋脑负责层谱抽象的全局认知与推理，算脑负责分而治之的演算与推理，两脑协同连接整体理解、局部计算与有效行动。",
    ),
    (
        "The Mou brain performs hierarchical abstraction and global cognition; the Suan brain performs divide-and-conquer calculation and reasoning. Together they connect whole-system understanding with local computation.",
        "“Zhi” refers to the scientific principles of cognition and strategic design; “Neng” refers to the engineering principles and capability for effective action. Intelligence, in the Chinese sense, is their unity and requires action. The Mou brain performs hierarchically abstracting global recognition and reasoning; the Suan brain performs divide-and-conquer calculation and reasoning. Together they connect whole-system understanding with local computation and effective action.",
    ),
    (
        "Hierarchical abstraction and global cognition let a model show what it observed and how it organised knowledge across levels of abstraction.",
        "Hierarchically abstracting and global recognition and reasoning let a model show what it observed and how it organised knowledge across levels of abstracting.",
    ),
    (
        "Use hierarchical abstraction to connect molecular, cellular, and system scales, building interpretable relations and reasoning across levels.",
        "Use hierarchically abstracting to connect molecular, cellular, and system scales, building interpretable relations and reasoning across levels.",
    ),
]


def main() -> int:
    if len(sys.argv) != 2:
        print("usage: patch_terminology_release.py RELEASE_ROOT", file=sys.stderr)
        return 2
    root = Path(sys.argv[1]).resolve()
    if not (root / "index.html").is_file():
        print(f"not a static release root: {root}", file=sys.stderr)
        return 2

    changed_files = 0
    replacement_hits = 0
    for path in [*root.rglob("*.html"), *root.rglob("*.js")]:
        text = path.read_text(encoding="utf-8")
        original = text
        for old, new in REPLACEMENTS:
            hits = text.count(old)
            if hits:
                text = text.replace(old, new)
                replacement_hits += hits
        if text != original:
            path.write_text(text, encoding="utf-8")
            changed_files += 1

    print(f"patched {changed_files} files with {replacement_hits} exact replacements")
    if replacement_hits < 20:
        print("too few replacements; refusing an incomplete release", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
