"use client";

import { useEffect, useState } from "react";

type Lang = "zh" | "en";
type Term = [string, string, string, string];

const terms: Term[] = [
  ["谋算智能", "MouSuan Intelligence (MSI); MouSuan recognition and agency", "由“谋”与“算”两种互补策略结合生成的智能。谋与算都是智能策略：谋进行层谱抽象的全局认知与推理、跨越抽象层谱的演算与推理并更新编码树；算进行计算与逻辑推理。", "Intelligence generated by combining Mou and Suan, two complementary strategies. Intelligence is the provisional short rendering; recognition and agency makes the cognition–action duality explicit."],
  ["智", "Strategically designing", "智能中的“智”：认知与策略设计的科学原理，负责从信息中形成可解释的策略设计。", "“Zhi” refers to the scientific principles of cognition and strategic design."],
  ["能", "Efficiently acting", "智能中的“能”：有效行动的工程原理与执行能力，把策略落实为可验证的行动。", "“Neng” refers to the engineering principles and capability for effective action."],
  ["智能", "Intelligence; recognition and agency", "“智”与“能”的统一：既能进行认知与策略设计，又具有能动性并能有效行动。英文暂用 Intelligence，也可用 recognition and agency 解释二分。智能需要行动。", "Chinese 智能 is provisionally rendered as Intelligence and can also be expressed as recognition and agency: the unity of recognition and strategic design with agency and efficient action."],
  ["博弈", "contest / strategic interaction; war (warfare-specific)", "多个主体或系统之间的体系对抗与策略互动；在战争特定语境中使用 war。", "A contest or strategic interaction among multiple agents or systems; use war in warfare-specific contexts."],
  ["谋", "Mou", "层谱抽象的全局认知与推理；其数学模型是编码树，属于信息科学概念。", "Hierarchically abstracting recognition; calculating and reasoning that cross the hierarchies of abstracting; updating the encoding tree. Mou is a strategy of hierarchically abstracting global recognition and reasoning."],
  ["层谱抽象", "hierarchically abstracting", "跨越层级组织复杂世界，形成能够被观察、编码并表示为数据结构的组织。", "Organising a complex world across a spectrum of hierarchies so that it can be observed, encoded, and represented as a data structure."],
  ["编码树", "encoding tree", "层谱抽象的数学模型，用树结构表示从局部到整体的层级组织。", "The mathematical model of hierarchically abstracting, representing an organisation from local parts to the whole as a tree."],
  ["全局认知", "global recognition and reasoning", "从整体结构与关系出发认知并推理信息世界，而不只拟合局部相关性。", "Understanding and reasoning about the information world from the whole-system structure and relations, rather than from local correlations alone."],
  ["跨越抽象层谱的演算与推理", "calculating and reasoning that cross the hierarchies of abstracting", "在不同抽象层之间传递信息、进行演算与推理，使整体目标能够落到局部行动。", "Calculating and reasoning that cross the hierarchies of abstracting so that information and global objectives can reach local action."],
  ["更新编码树", "updating the encoding tree", "依据新的观察、结构和策略结果更新编码树。", "Updating the encoding tree from new observations, structures, and strategy results."],
  ["算", "Suan", "计算与分而治之；属于经典数学、物理概念，把问题拆解并聚合结果。", "Computing and calculating, which is a strategy of logical reasoning."],
  ["计算", "Computing / Calculating", "对关系、状态与策略进行可执行、可验证的运算。", "Computing and calculating, which is a strategy of logical reasoning over relations, states, and strategies."],
  ["分而治之", "divide-and-conquer", "把复杂问题拆成子问题，分别计算，再组合为整体结果。", "Decomposing a complex problem into subproblems, solving them, and combining the results."],
  ["策略", "Strategy", "一种行动、操作或者算子。", "An action, an operation, or an operator."],
  ["智能策略", "intelligence strategy", "由“智”的策略性地设计与“能”的高效地行动统一形成的策略；谋与算都是智能策略。", "A strategy unifying Zhi’s strategically designing and Neng’s efficiently acting. Mou and Suan are both intelligence strategies."],
  ["生成策略", "Generating strategy", "生成信息的策略。", "A strategy that generates information."],
  ["解码策略", "Decoding strategy", "解码信息或消除不确定性的策略。", "A strategy to decode information or eliminate uncertainty."],
  ["解码信息", "decoded information", "经解码策略消除不确定性后得到的可用信息。", "Usable information obtained after a decoding strategy eliminates uncertainty."],
  ["生成信息", "generated information", "由生成策略在约束、演化或观察中形成的可用信息。", "Usable information formed by a generating strategy under constraints, evolution, or observation."],
  ["公理化科学原理", "Axiomatized Science Principles", "以公理或定律、定义和可验证推论组织科学知识体系。", "A scientific knowledge system organised by axioms or law, definitions, and verifiable deductions."],
  ["信息原理", "Information principles", "研究信息世界中确定性、不确定性及其相互转化的基本科学原理。", "The fundamental scientific principles governing certainty, uncertainty, and their transformations in the information world."],
  ["信息的数学原理", "Mathematical principles of information", "以层谱抽象为总方法，以信息演算、信息解码与信息生成为主要支柱的数学原理体系。", "A mathematical system based on hierarchical abstraction, with information calculus, information decoding, and information generation as its principal pillars."],
  ["信息科学", "information science", "研究信息的表示、演算、解码、生成及其在系统中的组织规律。", "The study of how information is represented, calculated, decoded, generated, and organised in systems."],
  ["信息的模型", "model of information", "以层谱抽象策略表征信息世界中对象、关系、状态及其演化的模型。", "A model that represents objects, relations, states, and evolution in the information world through hierarchical-abstracting strategy."],
  ["观察学习的信息模型", "information model of learning from observing", "以观察获得的信息为输入，经解码与生成形成可验证知识、策略或结构的模型。", "A model in which information acquired through observation is decoded and generated into verifiable knowledge, strategy, or structure."],
  ["自我意识的信息模型", "information model of awareness", "表征主体自身状态、确定性与不确定性及其转化，并判断利害的模型。", "A model representing a subject’s own state, certainty and uncertainty, their transformations, and their benefits or harms."],
  ["谋算博弈模型", "model of MouSuan contest and strategic interaction", "表征多个系统间体系对抗与策略互动、谋算策略生成及可能结果评估的模型；战争语境可使用 war。", "A model representing MouSuan contest and strategic interaction among systems, strategy generation, and evaluation of possible outcomes; war is used in warfare-specific contexts."],
  ["决策的信息模型", "information model of decision", "在层谱抽象与局部逻辑推理之间形成可验证决策的模型。", "A model that forms verifiable decisions between hierarchical abstraction and local logical reasoning."],
  ["系统协同行动模型", "system cooperative-action model", "表征多主体、多系统协同行动、分工与结果整合的模型。", "A model of cooperative action, division of work, and result integration among agents or systems."],
  ["系统验证模型", "system verification model", "以可验证原则判定系统行动、结果及获利或受害关系的模型。", "A model that verifies system actions, outcomes, and benefit-or-harm relations using verifiable principles."],
  ["机器智能", "machine intelligence", "以信息科学与计算科学原理形成、可解释并可验证的机器智能。", "Machine intelligence formed through principles of information science and computer science, explainable and verifiable."],
  ["双脑（左右半脑）体系结构", "dual-brain (left–right brain) architecture", "由两个互补脑区构成的体系结构：一侧承担层谱抽象的全局认知与推理，另一侧承担计算与逻辑推理。", "An architecture of two complementary brains: one performs hierarchically abstracting global recognition and reasoning, while the other performs computing and logical reasoning."],
  ["谋算双脑体系结构", "MouSuan dual-brain (left–right brain) architecture", "谋脑负责层谱抽象的全局认知与推理、跨越抽象层谱的演算与推理和编码树更新；算脑负责计算与逻辑推理，二者形成闭环。", "An architecture in which the Mou brain performs hierarchically abstracting global recognition and reasoning, calculating and reasoning across the hierarchies of abstracting, and encoding-tree updating, while the Suan brain performs computing and calculating as a strategy of logical reasoning."],
  ["谋算智能机", "MouSuan intelligent machine", "以谋算智能原理实现观察、解码、生成、计算、决策、行动与验证的智能机。", "An intelligent machine based on MouSuan Intelligence that observes, decodes, generates, calculates, decides, acts, and verifies."],
  ["谋算双脑体系结构智能机", "MouSuan dual-brain architecture intelligent machine", "以谋算双脑体系结构实现观察、解码、生成、计算、决策、行动与验证的智能机。", "An intelligent machine that uses the MouSuan dual-brain architecture to observe, decode, generate, calculate, decide, act, and verify."],
  ["孙子模型", "Sun Tzu Model", "基于信息世界科学原理的谋算智能模型；是面向层谱设计和高效行动的有原理、可解释世界模型，形成民用版与军用版。", "A model of MouSuan Intelligence: a principled, explainable world model for hierarchical design and efficient action, with civilian and military versions."],
  ["孙子机（谋算机）", "Sun Tzu Machine (MouSuan machine)", "基于信息世界科学原理的谋算双脑体系结构智能机；有原理、可解释的智能机。", "A MouSuan dual-brain architecture intelligent machine based on the scientific principles of the information world; a principled, explainable intelligent machine."],
  ["信息原理的具身智能", "Information-principled embodied intelligence", "以自我意识的信息模型为核心，在真实身体、传感器和环境中观察、学习、行动并验证。", "Embodied intelligence grounded in information principles and an information model of awareness, supporting observation, learning, action, and verification in a body and environment."],
  ["智能机", "intelligent machine", "中文网站统一使用的正式简称；指具备原理、解释与验证能力的智能机。", "The standard Chinese short form for an intelligent machine with principles, explanations, and verification."],
  ["智能机器人", "intelligent robot", "具备身体、传感器和行动能力的智能机；保留“机器人”这一完整术语。", "An intelligent machine with a body, sensors, and physical action; the complete robot term is retained."],
];

const copy = {
  zh: {
    back: "← 返回研究主页", toggle: "EN", eyebrow: "知识库 · 术语 Wiki", title: "谋算智能术语 Wiki", lead: "研究体系中的中英术语基准，涵盖信息原理、信息的数学原理、谋、算、智、能、机器智能、层谱抽象、编码树与信息模型。", pdf: "下载术语审核 PDF", table: ["中文术语", "统一英文", "中文含义", "English meaning"], note: "翻译约定：智涉及认知与策略设计，能涉及能动性与高效行动；中文“智能”暂用 Intelligence，同时可用 recognition and agency 表达其二分，但均不视为完全对等翻译。谋算智能科学技术的正式英文名称为 Science and Technology of MouSuan Strategy；其中 Mou 与 Suan 都是智能策略。“博弈”按语境使用 contest / strategic interaction，战争特定语境使用 war。", source: "正式定义、命题与证明见原始专著和论文。"
  },
  en: {
    back: "← Back to research hub", toggle: "中", eyebrow: "KNOWLEDGE BASE · TERMINOLOGY WIKI", title: "MouSuan Intelligence terminology Wiki", lead: "This is the team’s canonical Chinese-English terminology page. It standardises Information principles and Mathematical principles of information, defines Zhi through strategic design, Neng through agency and action, and fixes the information models used across the research system.", pdf: "Download terminology review PDF", table: ["Chinese term", "Canonical English", "中文含义", "English meaning"], note: "Translation convention: Chinese 智能 is provisionally rendered as Intelligence and may also be expressed as recognition and agency; neither is treated as a completely equivalent translation. The formal English name for 谋算智能科学技术 is Science and Technology of MouSuan Strategy; Mou and Suan are both intelligence strategies. 博弈 is rendered as contest / strategic interaction, with war used in warfare-specific contexts.", source: "This is a public concept page; consult the research hub and library for formal definitions and papers."
  }
};

export default function TerminologyWikiPage() {
  const [lang, setLang] = useState<Lang>("zh");
  useEffect(() => {
    setLang(new URLSearchParams(window.location.search).get("lang") === "en" ? "en" : "zh");
  }, []);
  const changeLang = (next: Lang) => {
    setLang(next);
    const url = new URL(window.location.href);
    if (next === "en") url.searchParams.set("lang", "en");
    else url.searchParams.delete("lang");
    window.history.replaceState(null, "", `${url.pathname}${url.search}${url.hash}`);
  };
  const c = copy[lang];
  return <main className="wiki-page">
    <header className="wiki-nav"><a className="brand" href={lang === "en" ? "/?lang=en" : "/"}><span className="brand-symbol"><img src="/logo-encoding-tree.svg" alt="" /></span><b>STRUCTURAL<br />INTELLIGENCE</b></a><a className="wiki-back" href={lang === "en" ? "/?lang=en" : "/"}>{c.back}</a><button onClick={() => changeLang(lang === "zh" ? "en" : "zh")}>{c.toggle}</button></header>
    <section className="wiki-hero"><div className="wiki-hero-inner"><p className="overline">{c.eyebrow}</p><h1>{c.title}</h1><p>{c.lead}</p></div></section>
    <section className="wiki-body shell"><a className="wiki-pdf-link" href="/mousuan-terminology-review.pdf" target="_blank" rel="noreferrer">{c.pdf} ↗</a><div className="wiki-table-wrap"><table><thead><tr>{c.table.map((heading) => <th key={heading}>{heading}</th>)}</tr></thead><tbody>{terms.map(([zh, en, meaningZh, meaningEn]) => <tr key={zh}><th scope="row">{zh}</th><td><code>{en}</code></td><td>{meaningZh}</td><td>{meaningEn}</td></tr>)}</tbody></table></div><p className="wiki-note">{c.note}</p><p className="wiki-source">{c.source}</p></section>
  </main>;
}
