"use client";

import { useEffect, useState } from "react";

type Lang = "zh" | "en";
type Term = [string, string, string, string];

const terms: Term[] = [
  ["谋算智能", "MouSuan Strategy (MSI)", "由“谋”与“算”两种互补策略结合生成的智能：谋进行层谱抽象的全局认知与推理、跨越抽象层谱的演算与推理并更新编码树；算进行计算与逻辑推理。", "The intelligence that is generated by combining Mou and Suan: Mou performs hierarchically abstracting global recognition and reasoning, calculating and reasoning that cross the hierarchies of abstracting, and encoding-tree updating; Suan performs computing and calculating as a strategy of logical reasoning."],
  ["智", "Strategically designing", "智能中的“智”：认知与策略设计的科学原理，负责从信息中形成可解释的策略设计。", "“Zhi” refers to the scientific principles of cognition and strategic design."],
  ["能", "Efficiently acting", "智能中的“能”：有效行动的工程原理与执行能力，把策略落实为可验证的行动。", "“Neng” refers to the engineering principles and capability for effective action."],
  ["智能", "Intelligence", "“智”与“能”的统一：既能进行策略设计，又能有效行动。智能需要行动。", "Intelligence, in the Chinese sense, is the unity of the two: strategically designing and efficiently acting. Intelligence requires action."],
  ["谋", "Mou", "层谱抽象的全局认知与推理；其数学模型是编码树，属于信息科学概念。", "Hierarchically abstracting recognition; calculating and reasoning that cross the hierarchies of abstracting; updating the encoding tree. Mou is a strategy of hierarchically abstracting global recognition and reasoning."],
  ["层谱抽象", "hierarchically abstracting", "跨越层级组织复杂世界，形成能够被观察、编码并表示为数据结构的组织。", "Organising a complex world across a spectrum of hierarchies so that it can be observed, encoded, and represented as a data structure."],
  ["编码树", "encoding tree", "层谱抽象的数学模型，用树结构表示从局部到整体的层级组织。", "The mathematical model of hierarchically abstracting, representing an organisation from local parts to the whole as a tree."],
  ["全局认知", "global recognition and reasoning", "从整体结构与关系出发认知并推理信息世界，而不只拟合局部相关性。", "Understanding and reasoning about the information world from the whole-system structure and relations, rather than from local correlations alone."],
  ["跨越抽象层谱的演算与推理", "calculating and reasoning that cross the hierarchies of abstracting", "在不同抽象层之间传递信息、进行演算与推理，使整体目标能够落到局部行动。", "Calculating and reasoning that cross the hierarchies of abstracting so that information and global objectives can reach local action."],
  ["更新编码树", "updating the encoding tree", "依据新的观察、结构和策略结果更新编码树。", "Updating the encoding tree from new observations, structures, and strategy results."],
  ["算", "Suan", "计算与分而治之；属于经典数学、物理概念，把问题拆解并聚合结果。", "Computing and calculating, which is a strategy of logical reasoning."],
  ["计算", "Computing / Calculating", "对关系、状态与策略进行可执行、可验证的运算。", "Computing and calculating, which is a strategy of logical reasoning over relations, states, and strategies."],
  ["分而治之", "divide-and-conquer", "把复杂问题拆成子问题，分别计算，再组合为整体结果。", "Decomposing a complex problem into subproblems, solving them, and combining the results."],
  ["策略", "Strategy", "一种行动、操作或者算子。", "An action, an operation, or an operator."],
  ["生成策略", "Generating strategy", "生成信息的策略。", "A strategy that generates information."],
  ["解码策略", "Decoding strategy", "解码信息或消除不确定性的策略。", "A strategy to decode information or eliminate uncertainty."],
  ["公理化科学原理", "Axiomatized Science Principles", "以公理或定律、定义和可验证推论组织科学知识体系。", "A scientific knowledge system organised by axioms or law, definitions, and verifiable deductions."],
  ["信息科学", "information science", "研究信息的表示、演算、解码、生成及其在系统中的组织规律。", "The study of how information is represented, calculated, decoded, generated, and organised in systems."],
  ["谋算双脑体系结构", "MouSuan dual-brain architecture", "谋脑负责层谱抽象的全局认知与推理、跨越抽象层谱的演算与推理和编码树更新；算脑负责计算与逻辑推理，二者形成闭环。", "An architecture in which the Mou brain performs hierarchically abstracting global recognition and reasoning, calculating and reasoning that cross the hierarchies of abstracting, and encoding-tree updating, while the Suan brain performs computing and calculating as a strategy of logical reasoning."],
  ["谋算智能机", "MouSuan intelligent machine", "以谋算智能原理实现观察、解码、生成、计算、决策、行动与验证的智能机。", "An intelligent machine based on MouSuan Strategy that observes, decodes, generates, calculates, decides, acts, and verifies."],
  ["谋算双脑体系结构智能机", "MouSuan dual-brain architecture intelligent machine", "以谋算双脑体系结构实现观察、解码、生成、计算、决策、行动与验证的智能机。", "An intelligent machine that uses the MouSuan dual-brain architecture to observe, decode, generate, calculate, decide, act, and verify."],
  ["孙子模型（谋算系统）", "Sun Tzu Model (MouSuan system)", "基于信息世界科学原理的谋算智能系统；是面向策略设计和有效行动的有原理、可解释世界模型，形成民用版与军用版。", "The Sun Tzu Model is a model of MouSuan Strategy—a principled, explainable model for strategic design and effective action, with civilian and military versions."],
  ["孙子机（谋算机）", "Sun Tzu Machine (MouSuan machine)", "基于信息世界科学原理的谋算双脑体系结构智能机；有原理、可解释的智能机。", "A MouSuan dual-brain architecture intelligent machine based on the scientific principles of the information world; a principled, explainable intelligent machine."],
  ["具身智能", "Embodied intelligence", "以自我意识的信息理论为核心，在真实身体、传感器和环境中观察、学习、行动并验证。", "Intelligence grounded in a body, sensors, and an environment, with self-awareness supporting observation, learning, action, and verification."],
  ["智能机", "intelligent machine", "中文网站统一使用的正式简称；指具备原理、解释与验证能力的智能机。", "The standard Chinese short form for an intelligent machine with principles, explanations, and verification."],
  ["智能机器人", "intelligent robot", "具备身体、传感器和行动能力的智能机；保留“机器人”这一完整术语。", "An intelligent machine with a body, sensors, and physical action; the complete robot term is retained."],
];

const copy = {
  zh: {
    back: "← 返回研究主页", toggle: "EN", eyebrow: "知识库 · 术语 Wiki", title: "谋算智能术语 Wiki", lead: "这是研究团队的中英术语基准页。它统一“谋、算、智、能、智能、层谱抽象、编码树、策略与公理化科学原理”等核心概念，并说明每个词在研究体系中的含义。", pdf: "下载术语审核 PDF", table: ["中文术语", "统一英文", "中文含义", "English meaning"], note: "翻译约定：智是 Strategically designing，能是 Efficiently acting；智能是二者的统一，并且必须包含行动。Mou 表示层谱抽象的全局认知与推理、跨越抽象层谱的演算与推理和编码树更新；Suan 表示 Computing / Calculating，即逻辑推理策略；Mou、Suan 使用大写拼音，hierarchically abstracting、global recognition and reasoning、divide-and-conquer 使用小写；Axiomatized Science Principles 使用首字母大写。", source: "该页面是公开的概念说明；正式定义与论文请参阅研究主页及文库。"
  },
  en: {
    back: "← Back to research hub", toggle: "中", eyebrow: "KNOWLEDGE BASE · TERMINOLOGY WIKI", title: "MouSuan Strategy terminology Wiki", lead: "This is the team’s canonical Chinese-English terminology page. It defines Zhi as strategically designing, Neng as efficiently acting, and Chinese intelligence as their unity; it also fixes the meanings of Mou, Suan, and the related terms used throughout the research system.", pdf: "Download terminology review PDF", table: ["Chinese term", "Canonical English", "中文含义", "English meaning"], note: "Translation convention: Zhi means strategically designing; Neng means efficiently acting; intelligence is their unity and requires action. Mou means hierarchically abstracting global recognition and reasoning, calculating and reasoning across the hierarchies of abstracting, and encoding-tree updating; Suan means computing and calculating as a strategy of logical reasoning. Keep Mou and Suan as capitalised pinyin; use lowercase hierarchically abstracting, global recognition and reasoning, and divide-and-conquer; capitalise Axiomatized Science Principles.", source: "This is a public concept page; consult the research hub and library for formal definitions and papers."
  }
};

export default function TerminologyWikiPage() {
  const [lang, setLang] = useState<Lang>("zh");
  useEffect(() => {
    setLang(new URLSearchParams(window.location.search).get("lang") === "en" ? "en" : "zh");
  }, []);
  const changeLang = (next: Lang) => {
    setLang(next);
    const url = new URL(window.location.href);
    if (next === "en") url.searchParams.set("lang", "en");
    else url.searchParams.delete("lang");
    window.history.replaceState(null, "", `${url.pathname}${url.search}${url.hash}`);
  };
  const c = copy[lang];
  return <main className="wiki-page">
    <header className="wiki-nav"><a className="brand" href={lang === "en" ? "/?lang=en" : "/"}><span>SI</span><b>STRUCTURAL<br />INTELLIGENCE</b></a><a className="wiki-back" href={lang === "en" ? "/?lang=en" : "/"}>{c.back}</a><button onClick={() => changeLang(lang === "zh" ? "en" : "zh")}>{c.toggle}</button></header>
    <section className="wiki-hero"><div className="wiki-hero-inner"><p className="overline">{c.eyebrow}</p><h1>{c.title}</h1><p>{c.lead}</p></div></section>
    <section className="wiki-body shell"><a className="wiki-pdf-link" href="/mousuan-terminology-review.pdf" target="_blank" rel="noreferrer">{c.pdf} ↗</a><div className="wiki-table-wrap"><table><thead><tr>{c.table.map((heading) => <th key={heading}>{heading}</th>)}</tr></thead><tbody>{terms.map(([zh, en, meaningZh, meaningEn]) => <tr key={zh}><th scope="row">{zh}</th><td><code>{en}</code></td><td>{meaningZh}</td><td>{meaningEn}</td></tr>)}</tbody></table></div><p className="wiki-note">{c.note}</p><p className="wiki-source">{c.source}</p></section>
  </main>;
}
