"use client";

import { useState } from "react";

type Lang = "zh" | "en";
type Term = [string, string, string, string];

const terms: Term[] = [
  ["谋算智能", "MouSuan Strategy (MSI)", "由“谋”与“算”两种互补策略生成的智能：以层谱抽象进行全局认知，以计算进行推理与行动。", "Intelligence generated by two complementary strategies: hierarchical abstraction for global cognition, and calculating for reasoning and action."],
  ["谋", "Mou", "层谱抽象的全局认知；其数学模型是编码树，属于信息科学概念。", "Hierarchical abstraction for global cognition; its mathematical model is the encoding tree, an information-science concept."],
  ["层谱抽象", "hierarchical abstraction", "跨越层级组织复杂世界，在不同抽象层上形成可观察、可解码的结构。", "Organising a complex world across a spectrum of hierarchies so that structures can be observed and decoded at different abstraction levels."],
  ["编码树", "encoding tree", "层谱抽象的数学模型，用树结构表达从局部到整体的层级组织。", "The mathematical model of hierarchical abstraction, representing organisation from local parts to the whole as a tree."],
  ["全局认知", "global cognition", "从整体结构与关系出发理解信息世界，而不只拟合局部相关性。", "Understanding the information world from its whole-system structure and relations, rather than fitting local correlations alone."],
  ["跨越抽象层谱的演算与推理", "cross-level calculus and reasoning", "在不同抽象层之间传递信息、进行演算与推理，使整体目标能够落到局部行动。", "Calculating and reasoning across abstraction levels so that information and global objectives can reach local action."],
  ["算", "Suan", "计算与分而治之；属于经典数学、物理概念，把问题拆解并聚合结果。", "Calculation and divide-and-conquer; a classical mathematical and physical concept that decomposes problems and aggregates results."],
  ["计算", "calculating / computing", "对关系、状态与策略进行可执行、可验证的运算。", "Executable and verifiable operations over relations, states, and strategies."],
  ["分而治之", "divide-and-conquer", "把复杂问题拆成子问题，分别计算，再组合为整体结果。", "Decomposing a complex problem into subproblems, solving them, and combining the results."],
  ["策略", "Strategy", "为达成目标而组织信息、选择行动与安排验证的总体方案。", "A plan that organises information, selects actions, and arranges verification to achieve a goal."],
  ["生成策略", "Generating strategy", "由认知与计算产生可执行的行动方案。", "Producing an executable course of action from cognition and calculation."],
  ["解码策略", "Decoding strategy", "从结构与观测中还原信息、关系和可用意义。", "Recovering information, relations, and usable meaning from structure and observation."],
  ["公理化科学原理", "Axiomatized Science Principles", "以明确公理、定义和可验证推论组织科学知识体系。", "A scientific knowledge system organised by explicit axioms, definitions, and verifiable deductions."],
  ["信息科学", "information science", "研究信息的表示、演算、解码、生成及其在系统中的组织规律。", "The study of how information is represented, calculated, decoded, generated, and organised in systems."],
  ["谋算双脑体系结构", "MouSuan dual-brain architecture", "谋脑负责层谱抽象与全局认知，算脑负责分而治之的计算与推理，二者形成闭环。", "An architecture in which the Mou brain performs hierarchical abstraction and global cognition while the Suan brain performs divide-and-conquer calculation and reasoning."],
  ["谋算双脑体系结构智能机器", "MouSuan dual-brain architecture intelligent machine", "以谋算双脑体系结构实现观察、解码、计算、决策、行动与验证的智能机器。", "An intelligent machine that uses the MouSuan dual-brain architecture to observe, decode, calculate, decide, act, and verify."],
];

const copy = {
  zh: {
    back: "← 返回研究主页", toggle: "EN", eyebrow: "知识库 · 术语 Wiki", title: "谋算智能术语 Wiki", lead: "这是研究团队的中英术语基准页。它把“谋、算、层谱抽象、编码树、策略与公理化科学原理”固定为可复用的翻译，并说明每个词在研究体系中的含义。", table: ["中文术语", "统一英文", "中文含义", "English meaning"], note: "翻译约定：Mou 与 Suan 保留拼音并首字母大写；hierarchical abstraction、global cognition、divide-and-conquer 使用小写；Axiomatized Science Principles 使用首字母大写。", source: "该页面是公开的概念说明；正式定义与论文请参阅研究主页及文库。"
  },
  en: {
    back: "← Back to research hub", toggle: "中", eyebrow: "KNOWLEDGE BASE · TERMINOLOGY WIKI", title: "MouSuan Strategy terminology Wiki", lead: "This is the team’s canonical Chinese-English terminology page. It fixes the translations of Mou, Suan, hierarchical abstraction, encoding tree, strategy, and Axiomatized Science Principles, with the intended meaning of each term in the research system.", table: ["Chinese term", "Canonical English", "中文含义", "English meaning"], note: "Translation convention: keep Mou and Suan as capitalised pinyin; use lowercase hierarchical abstraction, global cognition, and divide-and-conquer; capitalise Axiomatized Science Principles.", source: "This is a public concept page; consult the research hub and library for formal definitions and papers."
  }
};

export default function TerminologyWikiPage() {
  const [lang, setLang] = useState<Lang>("zh");
  const c = copy[lang];
  return <main className="wiki-page">
    <header className="wiki-nav"><a className="brand" href="/"><span>SI</span><b>STRUCTURAL<br />INTELLIGENCE</b></a><a className="wiki-back" href="/">{c.back}</a><button onClick={() => setLang(lang === "zh" ? "en" : "zh")}>{c.toggle}</button></header>
    <section className="wiki-hero"><div className="wiki-hero-inner"><p className="overline">{c.eyebrow}</p><h1>{c.title}</h1><p>{c.lead}</p></div></section>
    <section className="wiki-body shell"><div className="wiki-table-wrap"><table><thead><tr>{c.table.map((heading) => <th key={heading}>{heading}</th>)}</tr></thead><tbody>{terms.map(([zh, en, meaningZh, meaningEn]) => <tr key={zh}><th scope="row">{zh}</th><td><code>{en}</code></td><td>{meaningZh}</td><td>{meaningEn}</td></tr>)}</tbody></table></div><p className="wiki-note">{c.note}</p><p className="wiki-source">{c.source}</p></section>
  </main>;
}
